project_id = "ypjmqcuxruwpoidmjkiw"

[functions.chat]
verify_jwt = false

[functions.weather]
verify_jwt = false

[functions.currency]
verify_jwt = false

[functions.admin]
verify_jwt = false

[functions.map-proxy]
verify_jwt = false
